### ISSUE TITLE
custom config when initiate connection

### ISSUE THREAD

**Issue by ahsanulks** [go-rel/rel#148]
hi, can I setting connection timeout, max connection, etc when initiate a connection?

**Comment by Fs02** [comment]
hi, you should be able to set it from the driver directly, because it's functionality of the driver.
for example, in mysql you can set the [readTimeout](https://github.com/go-sql-driver/mysql#readtimeout) connection parameter, and in postgres you can set [connect_timeout](https://pkg.go.dev/github.com/lib/pq#hdr-Connection_String_Parameters) connection parameter.

```go
// open mysql connection.
adapter, err := mysql.Open("root@(127.0.0.1:3306)/rel_test?charset=utf8&parseTime=True&loc=Local&readTimeout=30s")
if err != nil {
	panic(err)
}
defer adapter.Close()

// initialize REL's repo.
repo := rel.New(adapter)
```

in case connection string is not enough, and you want to access [sql.DB](https://golang.org/pkg/database/sql/#DB) directly, you can use `sql.Open` and then pass it to [adapter.New](https://pkg.go.dev/github.com/go-rel/rel/adapter/mysql#New) method instead of using adapter.Open.

**Comment by ahsanulks** [comment]
i see. ok thx
