### ISSUE TITLE
Embedded structs are broken(ish)

### ISSUE THREAD

**Issue by jpicht** [go-rel/rel#296]
The [documentation](https://go-rel.github.io/basics/#embedded-structs) states that embedded structs are supported, but they are actually only supported if they are [anonymous](https://github.com/go-rel/rel/blob/master/document.go#L485). That's contrary to the example in the docs.

Is this that intended behavior?

**Comment by Fs02** [comment]
non anonymous embedded struct is still not supported at the moment, this need to be implemented soon
(if you want to try sending PR, let me know, thank you)

related issue: https://github.com/go-rel/rel/issues/277

**Comment by Fs02** [comment]
what shown in documentation should be supported (see: [unit test](https://github.com/go-rel/rel/blob/8347a7decaa853bb60cc79327680cd281c7eb21b/document_test.go#L86-L99))

**Comment by dranikpg** [comment]
Author of the anonymous structs feature here 😄 
I'll willingly take this up in the coming days if nobody wants to. I'd also stick with struct tags instead of automatic deduction. Not only because it's easier to understand (more explicit), but because it also might avoid collisions if interface deduction will be implemented in the future

**Comment by Fs02** [comment]
@dranikpg thank you, please feel free to do it 🎉
